services:
  rust-api: 
    build:
      context: ./backends/rust-api
    env_file: 
      - ./backends/.env
    ports: 
      - "8082:8000"  
    depends_on:
      - db:
        condition: service_healthy
    restart: unless-stopped

  python-api:
    build:
      context: ./backends/python-api 
    environment:
        PYTHONUNBUFFERED: "1" # This is used to ensure that the logs are printed in real-time and not buffered. 
    depends_on:
      - db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:18 
    volumes:
      - db-data:/var/lib/postgresql
      - ./backends/postgres/01-init.sh:/docker-entrypoint-initdb.d/01-init.sh:ro
      - ./backends/postgres/schema.sql:/opt/postgres/schema.sql:ro
      - ./backends/postgres/hardcoded_data:/opt/postgres/data:ro
    healthcheck:
      test:
          [
              "CMD-SHELL",
              "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
          ]
      interval: 5s
      timeout: 5s
      retries: 10  
    restart: unless-stopped
    
  frontend:
    build:
      context: ./frontend  
    environment:
      NUXT_API_BASE: http://rust-api:8000
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/code/frontend
      - frontend-node-modules:/code/frontend/node_modules
    depends_on:
        rust-api:
            condition: service_started
        python-api:
            condition: service_started
    restart: unless-stopped

volumes: 
  db-data:
  rust-target:
  frontend-node-modules:
