services:
  rust-api: 
    build:
      context: ./backends/rust-api
    env_file: 
      - ./backends/.env
    ports: 
      - "4040:8000" 
    volumes:
      - ./backends/rust-api:/code/rust-api
    depends_on:
      - db

  python-api:
    build:
      context: ./backends/python-api
    env_file: 
      - ./backends/.env
    environment:
        PYTHONUNBUFFERED: "1" # This is used to ensure that the logs are printed in real-time and not buffered.
    ports: 
      - "4041:8001" 
    volumes: 
      - ./backends/python-api:/code/python-api
    depends_on:
      - db

  db:
    image: postgres:18
    env_file: 
      - ./backends/.env 
    ports:
      - "5555:5432"
    volumes:
      - db-data:/var/lib/postgresql
      - ./backends/postgres/01-init.sh:/docker-entrypoint-initdb.d/01-init.sh:ro
      - ./backends/postgres/schema.sql:/opt/postgres/schema.sql:ro
      - ./backends/postgres/hardcoded_data:/opt/postgres/data:ro
    healthcheck:
      test:
          [
              "CMD-SHELL",
              "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
          ]
      interval: 5s
      timeout: 5s
      retries: 10  
    
  frontend:
    build:
      context: ./frontend 
    env_file:
      - ./frontend/.env
    ports:
      - "3001:3000" 
    volumes:
      - ./frontend:/code/frontend
      - frontend-node-modules:/code/frontend/node_modules
    depends_on:
      - rust-api
      - python-api

volumes: 
  db-data:
  rust-target:
  frontend-node-modules: